[package]
name = "foxy"
version = "0.1.0"
edition = "2021"
authors = ["GTLugo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kemono_transform = { version = "0.1", path = "../kemono_transform" }

# logging
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-unwrap = "0.10.0"

# rendering
vulkano = "0.32.3"
vulkano-shaders = "0.32.0"
vulkano-win = "0.32.0"
winit = "0.27" # older version required for vulkano-win

# utilities
#bytemuck = { version = "1.13.0", features = [ "derive" ] }
#glam = { version = "0.22.0", features = ["bytemuck"] }
#image = { version = "0.24.5", features = ["png", "jpeg"] }
#rgb = { version = "0.8.34", features = ["bytemuck"] }
#uuid = { version = "1.2.2", features = ["v4", "fast-rng"] }

[[example]]
name = "foxy_example"